package com.sarthakpawar.ENUMS;

public enum NotificationType {
    BOOKING_CONFIRMATION,
    BOOKING_CANCELLATION,
    CHECK_IN_REMINDER,
    CHECK_OUT_REMINDER,
    CHECK_IN_CONFIRMATION,
    CHECK_OUT_CONFIRMATION,
    PAYMENT_SUCCESS,
    PAYMENT_FAILED,
    REVIEW_REQUEST,
    PROMOTIONAL,
    GENERAL
}
